### PR TITLE
Use GitHub Actions to build containers

### PR DESCRIPTION
**Pull request by rsdy**

### CODE REVIEW

**Comment by rhdxmr** [comment]
I'll look into it soon

**Comment by rhdxmr** [comment]
@rsdy When I merge this PR in my forked repository, this error occurs.
```
"docker push" requires exactly 1 argument.
See 'docker push --help'.

Usage:  docker push [OPTIONS] NAME[:TAG]

Push an image or a repository to a registry
Error: Process completed with exit code 1.
```

It seems that the expressions below are evaluated into empty values maybe?

```
          docker push ${{ needs.build.outputs.ubuntu2004.image_id }}
          docker push ${{ needs.build.outputs.ubuntu1804.image_id }}
          docker push ${{ needs.build.outputs.rawhide.image_id }}

```

**Comment by rsdy** [comment]
@rhdxmr That's possible. I'm not sure why that would be the case, I guess I'll need to take a closer look.

However, the [GitHub documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs) does say this is the way to pass on strings to subsequent steps, and there is some variable checking in the engine, as I've managed to run into failures.

**Comment by rhdxmr** [comment]
@rsdy 
I learned that each of jobs is isolated so images built at a job are not shown at next push job.
So separated jobs are merged into one build-and-push job.
And also some variables are modified.
You can check this out: https://github.com/rhdxmr/build-images/commit/e6ae3d62a738c7f3d4c8528e570d23d0b57bf606

**Comment by rsdy** [comment]
@rhdxmr Turns out it was a simple copy-paste error that didn't get caught by the engine. Passing data to subsequent jobs now works on my fork as you can see here: https://github.com/rsdy/build-images/runs/2269539675

**Comment by rhdxmr** [comment]
@rsdy your fix ends up failure..
You can pass output data to next job but the images built by build job are not passed.
I guess that build job is running under a container and push job is running under another container.

**Comment by rsdy** [comment]
Ah sorry, you are right! However, build + push in one step will not work if we want to verify changes in PRs, as they won't have write access to the package repository. There needs to be a separate build step that checks if the containers can be built at all. Building twice seems like a waste...

**Comment by rsdy** [comment]
@rhdxmr This actually seems to work now. Please take a look at the last commit, I've modified your code a little to make `push` conditional.

**Review by rhdxmr — APPROVED** [review]
I pulled the new image (built by my forked repo) from ghcr and checked that building redbpf completes successfully.
Good to merge this PR.

**Pull request merged**
